### ISSUE TITLE
opx-switch-shell : KeyError: 'base-switch/diag_shell/output/result'

### ISSUE THREAD

**Issue by maq123** [open-switch/opx-nas-common#17] opened 2017-06-23 10:12 UTC
I'm using OPX with Dell S6000.
Seems CPS is not returning the result?

```
admin@OPX:~$ opx-switch-shell "l3 egress show"
Traceback (most recent call last):
  File "/usr/bin/opx-switch-shell", line 34, in <module>
    print str(l[0]['change']['data']['base-switch/diag_shell/output/result'])
KeyError: 'base-switch/diag_shell/output/result'
```

```
admin@OPX:~$ dpkg -l | grep -w  opx-nas-common
ii  opx-nas-common                 1.0.1                            amd64        This package contains common utilities for the network abstraction component.
```

**Comment by jghalam** [comment] 2017-06-23 11:46
Try the command with "sudo". CPS commands require root privileges. 
Thanks,
Joe

**Comment by maq123** [comment] 2017-06-23 14:12
Thanks @jghalam , it did the trick :)
It works from an unprivileged account on Dell OS10 so it got me confused.
Perhaps it could be made like that on OPX as well.

**Comment by Ragsboss** [comment] 2017-10-10 17:50
I'm seeing a different error..

```
root@s2:~# sudo opx-ethtool e101-002-0
Traceback (most recent call last):
  File "/usr/bin/opx-ethtool", line 278, in <module>
    main(sys.argv[1:])
  File "/usr/bin/opx-ethtool", line 262, in main
    ethtool_show_interface(argv)
  File "/usr/bin/opx-ethtool", line 83, in ethtool_show_interface
    if obj.get_attr_data('base-pas/media/dell-qualified') == 1:
  File "/usr/lib/opx/cps_object.py", line 305, in get_attr_data
    raise ValueError(attr + "does not exist in the obect")
ValueError: base-pas/media/dell-qualifieddoes not exist in the obect
root@s2:~# systemctl status opx-pas
● opx-pas.service - This PAS service is to initialize platform.
   Loaded: loaded (/lib/systemd/system/opx-pas.service; enabled)
   Active: active (running) since Mon 2017-08-07 17:05:46 UTC; 2 months 3 days ago
 Main PID: 915 (opx_pas_service)
   CGroup: /system.slice/opx-pas.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
root@s2:~# systemctl status opx-cps
● opx-cps.service - The CPS service is responsible for supporting communcation between applications
   Loaded: loaded (/lib/systemd/system/opx-cps.service; static)
   Active: active (running) since Mon 2017-08-07 17:04:27 UTC; 2 months 3 days ago
 Main PID: 762 (opx_cps_service)
   CGroup: /system.slice/opx-cps.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
root@s2:~# systemctl status opx-cpsc^C
root@s2:~# cat /etc/OPX-release-version 
OS_NAME="OPX-Base-Dell"
OS_VERSION="2.1.0"
PLATFORM="S6000-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch Base Blue Print 1.0.0"
BUILD_VERSION="2.1.0(26)"
BUILD_DATE="2017-07-14T23:29:12+0000"
INSTALL_DATE="2017-07-31T15:59:27+0000"
root@s2:~# opx-show-version 
OS_NAME="OPX-Base-Dell"

OS_VERSION="2.1.0"

PLATFORM="S6000-ON"

ARCHITECTURE="x86_64"

INTERNAL_BUILD_ID="OpenSwitch Base Blue Print 1.0.0"

BUILD_VERSION="2.1.0(26)"

BUILD_DATE="2017-07-14T23:29:12+0000"

INSTALL_DATE="2017-07-31T15:59:27+0000"

SYSTEM_UPTIME= 9 weeks, 1 day, 47 minutes

SYSTEM_STATE= running

UPGRADED_PACKAGES=no
```

**Comment by maq123** [comment] 2017-10-10 17:58
@Ragsboss Does e101-002-0 even show up when you fire up `ip link` ?

**Comment by Ragsboss** [comment] 2017-10-10 18:44
No. That is another thing I'm desperately trying to figure out. After I added a network namespace named `management`, things seem very weird. I can't see any interface starting with `e101-` yet the `lldpctl` shows active neighbors with`e101-` interfaces..

```
root@s2:~# ip netns list
management
root@s2:~# ip link
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether ec:f4:bb:fc:d0:d8 brd ff:ff:ff:ff:ff:ff
root@s2:~# ip netns exec management ip link
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether ec:f4:bb:fc:d0:d8 brd ff:ff:ff:ff:ff:ff
root@s2:~# ip netns exec default ip link
Cannot open network namespace "default": No such file or directory
root@s2:~# lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    e101-030-0, via: LLDP, RID: 29, Time: 4 days, 05:32:28
  Chassis:     
    ChassisID:    mac 34:17:eb:f4:4e:cd
    SysName:      l3
    SysDescr:     Debian GNU/Linux 8 (jessie) Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-14) x86_64
    MgmtIP:       10.1.103.1
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, off
    Capability:   Station, off
  Port:        
    PortID:       mac 34:17:eb:f4:4e:fd
    PortDescr:    NAS## 0 109
-------------------------------------------------------------------------------
Interface:    e101-029-0, via: LLDP, RID: 30, Time: 4 days, 05:31:58

```

Do you have any clue?

**Comment by maq123** [comment] 2017-10-10 20:36
Then you most likely broke some configuration while playing with the switch and the process responsible for creating NPU attached interfaces does not start correctly.
I assume you tried rebooting? :)

**Comment by jeffyin-dell** [comment] 2017-10-12 19:57
Hi @Ragsboss , I think you're using a development build (pre-release) of OPX 2.1. Try getting the release version of the installer from https://archive.openswitch.net/installers/2.1.0/Dell-EMC/PKGS_OPX-2.1.0.0-installer-x86_64.bin 
opx-show-version should yield 2.1.0(0), not 2.1.0(26).

I noticed that opx-ethtool was failing on a cps-get of "base-pas/media/dell-qualified" -- that should have been corrected to "vendor-qualified" in the release version.

I am not sure about your namespace issue. If that is covered in the other issue you opened, then a developer will definitely be taking a look at it. If not, please open a new one with the steps to reproduce your issue from a fresh boot (using the installer I linked above).

**Comment by jeffyin-dell** [comment] 2017-10-25 20:38
Closing this issue for now, since the original problem was resolved.

**Closed as completed by jeffyin-dell** 2017-10-25 20:38 UTC
